export const REQUEST_AIRPORT = 'REQUEST_AIRPORT';
export const REQUEST_AIRPORT_SUCCESS = 'REQUEST_AIRPORT_SUCCESS';
export const REQUEST_AIRPORT_ERROR = 'REQUEST_AIRPORT_ERROR';

export const CHANGE_AIRPORT = 'CHANGE_AIRPORT';
export const CHANGE_AIRPORT_SUCCESS = 'CHANGE_AIRPORT_SUCCESS';
export const CHANGE_AIRPORT_ERROR = 'CHANGE_AIRPORT_ERROR';

