export const SEND_COMMAND = 'SEND_COMMAND';
export const SEND_COMMAND_SUCCESS = 'SEND_COMMAND_SUCCESS';
export const SEND_COMMAND_ERROR = 'SEND_COMMAND_ERROR';

export const SELECT_DISPLAY = 'SELECT_DISPLAY';
export const SELECT_DISPLAY_SUCCESS = 'SELECT_DISPLAY_SUCCESS';
export const SELECT_DISPLAY_ERROR = 'SELECT_DISPLAY_ERROR';

